### PR TITLE
feat(onReq): handle requests with body

### PR DESCRIPTION
**Pull request by adamlacombe**

### CODE REVIEW

**Comment by ronag** [comment]
I'm not sure I follow this. What are you trying to solve?

**Comment by adamlacombe** [comment]
Sorry, I should have explained. I was trying to make your package more plug and play friendly. 

Some of the examples provided in the readme don't provide the onReq option, but I ran into issues similar to #31 where my requests were hanging. I figured out that if I provided onReq and closed the request before returning it everything worked.

```
server.on('request', (req, res) => {
  proxy.web(req, res, {
    hostname: 'localhost'
    port: 9000,
    onReq: (req, options) => http.request(req).end()
  }, defaultWebHandler)
})
```

It also takes and includes any body content with the request so by default it'll handle POST / PUT requests.

Example:

```typescript
const h2server = http2.createSecureServer({
  allowHTTP1: true,
  key: acmeClient.key,
  cert: acmeClient.cert
});
h2server.listen(443, () => console.log('HTTPS server running on port: 443'));
h2server.on('request', async (req, res) => {
  proxy.web(req, res, {
    hostname: '127.0.0.1',
    port: 3007,
    protocol: 'http'
  }, defaultWebHandler)
});
```

**Comment by ronag** [comment]
None of this should be required. What version of Node are you running and can you give me a full example that reproduce the issue?

**Comment by adamlacombe** [comment]
Node version: `v10.16.0`

Leaving `onRes` undefined is working now in `5.0.32`.

[Here is a repo](https://github.com/adamlacombe/http2-proxy-issue) to reproduce the issues I was having with `onReq`.

Seems like my issue with POSTing only occurred when the content type was javascript. I'm using [body-parser](https://github.com/expressjs/body-parser) middleware for express. I haven't had the chance to debug any further, but it looks like this is unrelated to http2-proxy.

**Pull request closed without merging**
